### ISSUE TITLE
Which models is used? XGBoost? how to change its parameters?

### ISSUE THREAD

**Issue by Jami1141** [rsyi/pylift#16]
Hi @rsyi 

First of all, thanks for very good package.
I want to use your code for my data.
I have few questions. First is that, If I want to use XGBoost, where can I change the parameters? I am asking because my data is highly imbalanced. Therefore, I need to change the value of scale_pos_weight of XGBoost to balance my data.
The second question is that I don't understand the difference between your plots of uplift gain and lift!
Can you please very briefly explain here?

Thanks in advance

**Comment by rsyi** [comment]
To manually modify the model, you can pass arguments to the `.fit` method, and those will pass through to the `XGBRegressor`. For example, if you have a `TransformedOutcome` object called `up`, you can run `up.fit(your_param=xxx)`, where `your_param` is any valid `XGBRegressor` argument. 

And yes, uplift gain and lift are confusing. In short, the lift plots tell you what the lift is in a particular bin, while, for the uplift gain (cumulative gain, adjusted Qini) curves, the y axis scales tells you how many incremental users you have obtained so far, cumulatively (it scales with the raw count, rather than a proportion). I'll add some plots to the docs to make this clearer.
