### ISSUE TITLE
Convert scoring methods to eval metrics

### ISSUE THREAD

**Issue by shaddyab** [rsyi/pylift#5]
Is there an easy way to convert the sklearn make_scorer metrics (e.g., _aqini_score, _qini_score, etc.) to eval functions that can be used with the 'eval_metric' argument in xgboost?

**Comment by shaddyab** [comment]
Followup: 
After further looking into this, I found that the main issue is that xgboost internally return DMatrix object for the prediction and actual data while most function in eval.py expect a list that can be sorted

**Comment by rsyi** [comment]
Thanks for looking into it @shaddyab!
I don't think this is possible, as far as I know. xgboost's objective function optimizes each split, and because Qini scores are calculated over rankings, there's no way to calculate this before all the splits are decided.

You can, however, use a custom objective that splits and corrects for imbalances in treatment and control (`from pylift.methods.derivatives import custom_objective`, then use `custom_objective` in `XGBRegressor(objective=custom_objective)`), and I'm working on making this the native functionality. The splits would then exactly minimize MSE between your prediction and the *true treatment effect*, which is what we generally go for :)

I'll probably write up some quick docs explaining this at some point. I'll try to remember to post here when I do.

**Comment by shaddyab** [comment]
My goal was to use these metrics as part of the 'fit' and 'evals_result' methods of xgboost to evaluate  after each epoch, and not after each split. Very similar to how the metrics are used as scoring_method in the sklearn Grid search and Random Search functions
